version: '3.9'

services:
  sqlserver:
    container_name: validacao-cg-sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "testeOITO8"
      ACCEPT_EULA: "Y"